name: tomato_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # icon 套件
  flutter_native_splash: ^2.4.6 # 動畫套件
  audioplayers: ^5.2.1 # 音樂播放套件
  flutter_local_notifications: ^17.2.1 # 通知套件
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3 # 顏色選擇器套件
  image_picker: ^0.8.7+5 # 圖片選擇器套件

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.2

flutter:
  assets:
    - assets/Tomato250-1.jpg
    - assets/IMG_0067.jpg
    - assets/birds-339196.mp3
    - assets/space.jpg

  uses-material-design: true